### ISSUE TITLE
Uploading code stuck at 50%

### ISSUE THREAD

**Issue by shankinsecs** [duinoapp/duinoapp-client#22]
We currently use Chromeduino at our school and would like to transition to the Duino App. Our students and facutly utilize chromebooks. We have attempted to upload code to an Arduino Uno from several different devices and continually the upload gets stuck at 50%. Here is the output we receive in the serial box.

**Comment by mrfrase3** [comment]
Hey there,

All that log is showing is that it compiled fine on the server. If you right-click on the application, select "inspect" a debug menu should open, navigate to the "console" tab.

Try to upload your code see if any errors appear in red. You can click on the errors to expand them out. If there are any, then could you upload a screenshot?

**Comment by mrfrase3** [comment]
Also, just a sanity check, have you tried disconnecting and reconnecting the device, and if that didn't work, rebooting the computer?

**Comment by shankinsecs** [comment]
![Screenshot 2021-04-21 8 21 45 PM](https://user-images.githubusercontent.com/82977196/115641800-6d4b7300-a2df-11eb-9b0d-0e6f1dce10b3.png)
We definitely have. We have also tried different boards and different devices. I do not see any errors in the console tab of the developer tools. Here is a screenshot.

**Comment by MrWollenburg** [comment]
Our school is having the same issue. 50% and it will not load beyond. We use Lenovo 500e Chromebooks. I have access to a windows machine with Arduino software on it and the code loads fine on it. Duino 2 always seemed to work, hoping this can be fixed.   :)

**Comment by shankinsecs** [comment]
We have tried on HP G5 G6 and G7 chromebooks, as well as a pixelbook and the Dell 3100 EE chromebooks. Chromeduino 2 was working out for us previously as well but it no longer loads. Just a white screen.

**Comment by MrWollenburg** [comment]
Shankinsecs, a solution I'm using for my students right now is the following:

1.Navigate to https://edu.codebender.cc/class_demo
2. Copy student code.
3. Paste student code into URL bar
4. Copy code from URL (this puts it all into a single line of code, rather than multiple lines)
5. Delete code from codebender
5. Paste code into codebender
6. Upload code

![Temp code fix](https://user-images.githubusercontent.com/83072991/115874892-43db3600-a40a-11eb-8956-ad4c5d703bac.gif)


Hopefully this helps your school as a temp fix!

**Comment by mrfrase3** [comment]
Hmmm, I think this might be the timing issue. We've just gone into a Covid lockdown for the weekend where I live so I now have plenty of time to look into this.

Side note, I'm not a huge fan of code bender after they told me to fix their code for free which they charge people for. You should still be able to use chromeduino 2 until June or something, hard to get an exact date...

**Comment by MrWollenburg** [comment]
I'd love to use Duino 2, but unfortunately, we can't get passed the server list screen any more.

**Comment by shankinsecs** [comment]
> I'd love to use Duino 2, but unfortunately, we can't get passed the server list screen any more.

Same issue for us. Students who had previously used it are able to. However when I reset their settings and clear the cache it no longer works. We also aren't able to get it to work for new students who hadn't previously used it. Hopefully this information is helpful. We appreciate your time so much mrfrase3!

**Comment by mrfrase3** [comment]
I found some of the older servers were timing out which paused the loading of the servers until they were all loaded/timeout. try just waiting on the empty servers list for a few minutes.

**Comment by shankinsecs** [comment]
Unfortunately no matter how long I leave it sitting on any of our devices I am only getting a blank screen. ![image](https://user-images.githubusercontent.com/82977196/115905782-320a8a80-a42c-11eb-903a-5b47ae64ebbc.png)

**Comment by mrfrase3** [comment]
hm, I'd like to say that surprises me, but chromduino 2 has been so flaky that I'm not...

Anyway, I think I've fixed this, and I've staged a 3.2.1 update with it in [beta.duino.app](https://beta.duino.app). If someone could test and confirm that its fixed in beta, I'll deploy it into production.

**Comment by shankinsecs** [comment]
Still getting hung at 50% for me. Not getting any errors in the dev console but I´m going to keep trying and I´ll let you know.

**Comment by mrfrase3** [comment]
looks like the fix wasn't actually applied, I'm deploying version 3.2.2 now to beta. Sorry about that

**Comment by shankinsecs** [comment]
It appears to be working fine for us now. Thank you so much for your time. Our teachers will be thrilled.

**Comment by mrfrase3** [comment]
Cool, I've merged beta into production, you should now be able to use version 3.2.2 on https://duino.app/

Enjoy!

**Comment by MrWollenburg** [comment]
> Cool, I've merged beta into production, you should now be able to use version 3.2.2 on https://duino.app/
> 
> Enjoy!

The app works great again, thank you for your hard work! Hope the temp lockdown doesn't cause too much fuss with you guys.
